aws_error_utils/__init__.py,sha256=73sOoasHyZYcjIVNJC_OvWIEd6eAXoF0AQNdFJ8io24,846
aws_error_utils/aws_error_utils.py,sha256=mB9xVF3GKESFqvC9RQ8rq54tnbhz74yNUq2n3Q4UGsI,8219
aws_error_utils/py.typed,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
aws_error_utils-2.4.0.dist-info/LICENSE,sha256=9j8RqO8bPFqn4auDoWpegssMFBSlrw52EoRAO4PJyOA,11340
aws_error_utils-2.4.0.dist-info/WHEEL,sha256=y3eDiaFVSNTPbgzfNn0nYn5tEn1cX6WrdetDlQM4xWw,83
aws_error_utils-2.4.0.dist-info/METADATA,sha256=0hyPZp2NYdSbRk5dglOKwwQIAtJ1ljBxHym3DCBkxwc,9506
aws_error_utils-2.4.0.dist-info/RECORD,,
