aws_error_utils/__init__.py,sha256=73sOoasHyZYcjIVNJC_OvWIEd6eAXoF0AQNdFJ8io24,846
aws_error_utils/aws_error_utils.py,sha256=AbdX46Hg41ITLoIihdssnjAd83MlldIMQhT_kgKF3lI,8261
aws_error_utils/py.typed,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
aws_error_utils-2.5.0.dist-info/LICENSE,sha256=9j8RqO8bPFqn4auDoWpegssMFBSlrw52EoRAO4PJyOA,11340
aws_error_utils-2.5.0.dist-info/WHEEL,sha256=y3eDiaFVSNTPbgzfNn0nYn5tEn1cX6WrdetDlQM4xWw,83
aws_error_utils-2.5.0.dist-info/METADATA,sha256=UXY52aRV6rqt9zqNVzq63kQD8G8ve94FZVbFmqDv1W8,9506
aws_error_utils-2.5.0.dist-info/RECORD,,
